### ISSUE TITLE
Link to subdirectories

### ISSUE THREAD

**Issue by 100Errors** [steemscript/steemconnect#186]
Hey there.
Please link at steemconnect.com to subdirectories / important sites like
Docs: https://v2.steemconnect.com/docs/steemjs or https://steemconnect.com/docs/steemjs
Dashboard (if logged in): https://steemconnect.com/dashboard
Login (if not logged in): https://steemconnect.com/login

Otherwise it's really hard to find these sites

**Comment by bonustrack** [comment]
Related to #241
