### ISSUE TITLE
Display a report for better error analysis

### ISSUE THREAD

**Issue by gregory-latinier** [steemscript/steemconnect#211]
People are often asking for help when a sign operation doesn't work.
Instead of asking multiple questions or ask the user to show us logs, ... it would be nicer to have access to a page that would display a report the user could give or send to the concerned party.

We could have a small text below the `try again button` like this 

![image](https://user-images.githubusercontent.com/13222767/37764441-fe3cdd2c-2dc1-11e8-866f-81342be700c1.png)

This would lead to a page displaying essential information for debugging

We could prepare a formatted page showing
1/ The url used (for example : `/sign/vote?voter=ned&author=krnel&permlink=getting-too-personal-with-ai-assistants&weight=10000`)
2/ The complete parameters and operations broadcast
3/ The full stack of the blockchain error

This page would display FAQ and documentations link first and then suggest where to send this report either to steemit support, a discord channel or open a github issue if the user is sure that it's a bug

**Comment by Sambillingham** [comment]
Thank you, I'm sure this would allow me to fix #209. More than likely an issue with the parameters I am using but without the error response, it's guesswork to figure out what it is.
