### ISSUE TITLE
Add link to dashboard from homepage header

### ISSUE THREAD

**Issue by bonustrack** [steemscript/steemconnect#241]
Many users dont find a way to access dashboard, we should have a link on the homepage perhaps with Sign up | Log in.

**Comment by bonustrack** [comment]
We can have it full screen like that:
![image](https://user-images.githubusercontent.com/16245250/39302443-d01556dc-497c-11e8-8aeb-c6e1073297b2.png)

**Comment by bonustrack** [comment]
@pareshUD do you have the topnav for the homepage?

**Comment by pareshUD** [comment]
![steemconnect homepage](https://user-images.githubusercontent.com/8911074/40055560-fca1f280-5865-11e8-860a-c1219ae6f5d7.png)

**Comment by gregory-latinier** [comment]
This a user connected view. We also need the right top nav when the user is not connected please.
Thanks !

**Comment by gregory-latinier** [comment]
What you showed is when a user is already logged in SteemConnect.
We need the design when a new user is coming for the first time for instance. The login button or text

**Comment by pareshUD** [comment]
![steemconnect_banner](https://user-images.githubusercontent.com/8911074/40169091-d1f2883c-59e2-11e8-9ec4-deb1af181ea0.png)

When user is not logged in

**Comment by bonustrack** [comment]
Closing this issue it's not relevant for the new version.
