### ISSUE TITLE
Setup dedicated node for SteemConnect for server side usage

### ISSUE THREAD

**Issue by bonustrack** [steemscript/steemconnect#251]
SteemConnect is using public node api.steemit.com to connect to Steemd API. When this node is not working, 3p apps relying on SC canot broadcast transaction anymore. SteemConnect could have his own dedicated node. Steemd API url can remain secret since transaction for SC posting API happen on server side.

**Comment by gregory-latinier** [comment]
Depends on #250

**Comment by gregory-latinier** [comment]
How do you want to proceed with this ?
Should I setup a node first to test on a VM for instance and then we rent a server on AWS ?
