### ISSUE TITLE
Add version to javascript file app.min.js in index.hbs

### ISSUE THREAD

**Issue by gregory-latinier** [steemscript/steemconnect#256]
Right now when we release a new version the user has to refresh its browser cache to get the updated code. We could prevent that by adding a version value that would be updated before doing a release.

We could change 
`<script type="text/javascript" src="/js/app.min.js"></script>`
to 
`<script type="text/javascript" src="/js/app.min.js?v=0.1.1"></script>`

and before pushing the new PRs to production we have to create a PR whose sole purpose would be to update this value. 
It would be great to create a git tag matching this version each time we deploy.

We could also use the version in the package.json and use webpack to replace variables in the code. For example if we want to add the version in the footer.

**Comment by bonustrack** [comment]
This is done in new version, closing this issue
