### ISSUE TITLE
Don't ask for active key again for login if user already authorized the app

### ISSUE THREAD

**Issue by bonustrack** [steemscript/steemconnect#259]
When user is unlogged on steemconnect and try to login from an app, SC require user to type his active key again. The problem is that if user is unlogged from SC we don't know his username and if he already authorized the app so SC assume user not yet authorized. The proper flow would be to get the username first and check if user already authorize the app to define the lowest required key the user need to type.

**Comment by asgarth** [comment]
Any news or plan on this issue? I've integrates sc2 for login on https://steempeak.com and lot of users keep asking why they need the active key also when they already have authorized the application on steemconnect.

**Comment by bonustrack** [comment]
This issue is solved on new the version on steemconnect at https://beta.steemconnect.com. Please open another issue if you still having some issue to get it work.
