### ISSUE TITLE
Request / Idea: Log all actions sent to SteemConnect by Apps

### ISSUE THREAD

**Issue by gregory-latinier** [steemscript/steemconnect#265]
We currently don't log actions that go through SteemConnect. People can only check what happened by using steemd explorer but it doesn't reflect what really happened.

Since SteemConnect adds authority over an account, actions can happen without the user knowledge. Logging actions and offer search and filter capabilities would allow us, the user and app owners to track down more detailed information. For instance we could answer things like that:

- For user: my account voted for a post and I didn't do it. What access token was used by what app from what IP address ?
- For app owner: my app is acting funny people are complaining about miss use. Can I track the access and refresh tokens used by my app and from IP address ?

Detailed specs would be produced if we decide to implement this

**Comment by bonustrack** [comment]
Closing this issue, it's out of scope for now.
