### ISSUE TITLE
Support All URLs with a beginning string rather than do an exact match for Redirect URI

### ISSUE THREAD

**Issue by jm90m** [steemscript/steemconnect#297]
### Problem:

So whenever I create a release channel and try to test, the redirect URI is something like ` exp://exp.host/@jm90m/bsteem?release-channel=jm-test-branch`. And I am unable to login to steem connect using this

 ### Possible Solution:
It would be great to ALLOW all urls with the beginning string `exp://exp.host/@jm90m/bsteem`

**Comment by bonustrack** [comment]
Perhaps you can create your own endpoint, which redirect user to dynamic url with `exp://`. I don't think it's OAuth2 proof to allow all url with a beginning string.
