### ISSUE TITLE
/login/challenge route throwing AssertionError Expected version 128, instead got 2

### ISSUE THREAD

**Issue by lopugit** [steemscript/steemconnect#300]
when running the 

`accounts = await req.steem.api.getAccountsAsync([username]);`

line within the /login/challenge api route, I get this error

`
(node:25749) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Expected version 128, instead got 2
    at Function.fromWif (/home/lopu/git/steemconnect/dev/node_modules/@steemit/steem-js/lib/auth/ecc/src/key_private.js:186:20)
    at toPrivateObj (/home/lopu/git/steemconnect/dev/node_modules/@steemit/steem-js/lib/auth/memo.js:143:42)
    at encode (/home/lopu/git/steemconnect/dev/node_modules/@steemit/steem-js/lib/auth/memo.js:94:19)
    at router.all (/home/lopu/git/steemconnect/dev/routes/api.js:159:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

Any idea?

**Comment by lopugit** [comment]
Is it something to do with the WIF in the `.env`? What does WIF stand for?

indeed it is to do with that, I got my private key from v2.steemconnect.com/apps/@my-app

but now it says

`
UnhandledPromiseRejectionWarning: Error: Non-base58 character
    at Object.decode (/home/lopu/git/steemconnect/dev/node_modules/base-x/index.js:84:11)
    at Function.fromWif (/home/lopu/git/steemconnect/dev/node_modules/@steemit/steem-js/lib/auth/ecc/src/key_private.js:184:49)
`

**Comment by bonustrack** [comment]
WIF is a private key. You need to setup these config vars on your environment to get login challenge working: 
```
STEEMD_URL=https://api.steemit.com
STEEMD_URL_SERVER=https://api.steemit.com
BROADCASTER_USERNAME=username
BROADCASTER_POSTING_WIF=key <- A private posting key
JWT_SECRET=secret
DEBUG=sc2:*
DATABASE_URL=database_url
CSP_DEFAULT='self'
CSP_SCRIPT_SRC='self','unsafe-eval','unsafe-inline'
CSP_CONNECT_SRC='self',*.steemit.com
CSP_FRAME_SRC='self'
CSP_STYLE_SRC='self','unsafe-inline'
CSP_IMG_SRC='self',steemitimages.com,steemit-production-imageproxy-thumbnail.s3.amazonaws.com,data:
CSP_FONT_SRC='self'
```

Application proxy accounts are managed by SteemConnect, you canot get the private key of an app you create.

**Comment by lopugit** [comment]
@bonustrack 

got it working with my private account but, seems a bit odd that you can use app accounts for steemconnect-sdk but not for broadcasting, and I paid for the app creation thing, can you explain the difference a bit or if maybe apps should have their own private keys? Why do you have to pay for an app?

**Comment by bonustrack** [comment]
If 3p apps own their proxy account key we (SteemConnect) would not be able to protect end users if the key get stolen or if the 3p app act in malicious way. If this happen it would require every each users of the app to revoke the app proxy account. With current implementation if something goes wrong we can always desactivate the app without the need for end user to do something.
