### ISSUE TITLE
Steemconnect server error - Can't open steemconnect.com or user auth service for other apps.

### ISSUE THREAD

**Issue by nirvanaitsolutions** [steemscript/steemconnect#315]
This bug is seen today morning itself. 

Expected: Able to log in via steemconnect.

Actual: Steemconnect login page sends application error. 

How to reproduce : go to busy.org or any steemconnect based app and try to log in. You will be redirected to steemconnect which is followed by server error.

**Comment by bonustrack** [comment]
There was a downtime with the server, it should be working as usual by now, can you confirm everything is working fine for you @nirvanaitsolutions ?

**Comment by daef** [comment]
I get a CORS fail for api.steemit.com
