### ISSUE TITLE
Request to add node selection function

### ISSUE THREAD

**Issue by lie7** [steemscript/steemconnect#333]
'steemconnect' seems to use only one node. Many users need to be able to select one of several validated nodes when they log in.

Some users may not be able to connect to the currently specified node. 
Of course, I think it is a problem of user internet environment.

**Comment by bonustrack** [comment]
Now on the new version of steemconnect at https://beta.steemconnect.com you can select a custom node on settings page https://beta.steemconnect.com/settings . I'm closing this issue if you're still having issues please open another issue.
