### ISSUE TITLE
Failed to load https://v2.steemconnect.com/api/me

### ISSUE THREAD

**Issue by BartolomeoItaliano** [steemscript/steemconnect#339]
I get following error if any user is trying to login through steem connect to my page. The page was working for quite some time and after last hard fork it stopped. What could be the reason?

I see steem connect working on page like dmania.lol or busy.org. Did I miss something?

> Failed to load https://v2.steemconnect.com/api/me: Response for preflight is invalid (redirect)
![przechwytywanie](https://user-images.githubusercontent.com/26720699/46255723-f93aec80-c4a0-11e8-8c2e-b2714f9027d4.PNG)

**Comment by jakipatryk** [comment]
Use https://steemconnect.com/api/me instead.

**Comment by BartolomeoItaliano** [comment]
Hi, but how to change it? I cannot find anything corresponding in documentation.

**Comment by bonustrack** [comment]
If you update to the latest version of the npm package `steemconnect` the proper baseURL will be set by default.
