### ISSUE TITLE
Is it possible to change the keys of an app account and turn it into a normal account?

### ISSUE THREAD

**Issue by lopugit** [steemscript/steemconnect#344]
We made the app account @weyoume for our busy interface fork but we'd like to use the @weyoume handle to make some posts and etc.. We'd like to change the keys over to the same keys as the @lopu account which if you check the psql apps table it'll have @lopu as the owner. 

And we're happy to rescind all the current tokens for it, we'll sign up a new @weapp account for app authentication purposes.

Please let us know ASAP if this is possible because we'd like to make some posts on the @weyoume handle.

Thanks a lot <3 

the @lopu public keys are:
POSTING
STM5YkH6wHsGmP2FXg9b4Hh6buEkScqNAYcFjfxAeSTUVXnpmD5Vg
ACTIVE
STM5SXwEK1HxF9u8HqMcg5KpyWb7evm8gqq1g8G3hNjssP151mNgP
OWNER
STM76YsQBDmkPkyWw3wv86rk84qnU29XQct8pPyxbxTRk1A8oQFMU
MEMO
STM81ac9SxVb93MJzUnqcb6MGA1aou7ySMEDneX98VihrgwFBAkgy

**Comment by bonustrack** [comment]
If you haven't used the app account yet it's possible to get it back yes. This is a manual process, please contact me on SteemDevs Discord.
