### ISSUE TITLE
Claim account 

### ISSUE THREAD

**Issue by stm12** [steemscript/steemconnect#346]
Is it possible to claim account using steemconnect?

**Comment by TimCliff** [comment]
Try: 
`https://steemconnect.com/sign/claim-account?fee=3.000%20STEEM&extensions=[]`
(Keep in mind this operation has a very high RC cost.)

**Comment by TimCliff** [comment]
Also, I should clarify the above URL is just to claim the discounted account. Creating the account using the claimed account is a separate step.

**Comment by bonustrack** [comment]
It should work with empty fee like that: https://steemconnect.com/sign/claim-account?fee=0.000%20STEEM&extensions=[]

**Comment by stm12** [comment]
> Also, I should clarify the above URL is just to claim the discounted account. Creating the account using the claimed account is a separate step.
> It should work with empty fee like that: [https://steemconnect.com/sign/claim-account?fee=0.000%20STEEM&extensions=[]](https://steemconnect.com/sign/claim-account?fee=0.000%20STEEM&extensions=%5B%5D)

Is it possible to create account using claimed account using steemconnect?

**Comment by bonustrack** [comment]
No it's not possible @stm12, we did not yet implemented a tool for that.
