### ISSUE TITLE
SDK error, invalid_grant, the token has invalid role

### ISSUE THREAD

**Issue by rubenmr** [steemscript/steemconnect#361]
I have a problem when I try to make a vote,
I get this message

error:  { [SDKError: sc2-sdk error]
  name: 'SDKError',
  error: 'invalid_grant',
  error_description: 'The token has invalid role' }

did you catch this error? how can I solve it?
thanks!

**Comment by bonustrack** [comment]
It seem that the access_token you are using is not valid. Is it possible that the token is older than 7 days? How did you generated the token?

**Comment by rubenmr** [comment]
but I got the token a few minutes before I tride to vote. 
I generated the token when I logged with SteemConnect.

**Comment by bonustrack** [comment]
Can you give me the login url you are using? The url should look like "steemconnect.com/oauth2/authorize..."

**Comment by rubenmr** [comment]
Of course: it's:
https://app.steemconnect.com/oauth2/authorize?client_id=apprsd&redirect_uri=https%3A%2F%2Flocalhost%3A4200%2Fv1&scope=login,vote,comment,delete_comment,comment_options,custom_json,claim_reward_balance

**Comment by rubenmr** [comment]
that url gives me an access_token I undestand, which is the token that the function of voting needs. please let me know.

**Comment by bonustrack** [comment]
The scope "login" should not be used if you want to broadcast posting operations. You can left the option array "scope" empty to request all posting scope, no need to list all of them. The final url would look like this: `https://steemconnect.com/oauth2/authorize?client_id=apprsd&redirect_uri=https%3A%2F%2Flocalhost%3A4200%2Fv1&scope=`

**Comment by rubenmr** [comment]
Thanks! I'll try it now!

**Comment by rubenmr** [comment]
that error continues.
![image](https://user-images.githubusercontent.com/30711015/52056708-f1fc1c00-2530-11e9-8912-ccc442b27d54.png)

the url is this: https://app.steemconnect.com/oauth2/authorize?client_id=apprsd&redirect_uri=https%3A%2F%2Flocalhost%3A4200%2Fv1&scope=

**Comment by bonustrack** [comment]
I tried with that url and i been able to vote with that token. Are you sure you are using the newly created access_token to broadcast a vote?

**Comment by rubenmr** [comment]
I understand. Maybe there is a problem with the code. May I see a snippet of your voting function? Sir

**Comment by bonustrack** [comment]
I used busy.org code but you can find a simple example here: https://github.com/steemscript/example-steemconnect-angular/blob/master/app.js#L57-L65

**Comment by rubenmr** [comment]
Thanks. At the moment I call that function in Postman, is it valid to pass the access_token as a authorization header in backend. after I got the acces_token from frontend?

**Comment by bonustrack** [comment]
You may not using the proper syntax, here is an example for the syntax: https://github.com/steemscript/steemconnect/wiki/OAuth-2#broadcast-a-transaction

**Comment by rubenmr** [comment]
is this the right syntax?

//without
var dsteem = require('dsteem');
const steem = new sc2.Initialize({
    app: 'apprsd', 
    callbackURL: 'https://localhost:4200/v1', 
    accessToken: '',
    scope: '',
});

function vote(req,res){
  var voter=req.body.voter;
  var aux=req.body.privateKey:
  var privateKey=dsteem.PrivateKey.fromString(aux);
  var author=req.body.author;
  var permlink=req.body.permlink;
  var weight=req.body.weight;

  const vote={
    voter,
    author,
    permlink,
    weight
  };

  steem.vote(vote,privateKey).then(
        function(result) {
            console.log('success:', result); },
         function(error) {
            console.log('error:', error);  }
  )

}

//with token
module.exports.isAuthenticated = (req, res, next) => {
  if (req.session.access_token)
      return next();

  res.redirect('/');
}

router.post('/vote', util.isAuthenticatedJSON, (req, res) => {
    let postId = req.body.postId
    let voter = req.session.steemconnect.name
    let author = req.body.author
    let permlink = req.body.permlink
    let weight = 10000

    steem.vote(voter, author, permlink, weight, function (err, steemResponse) {
      if (err) {
          res.json({ error: err.error_description })
      } else {
          res.json({ id: postId })
      }
    });
})

**Comment by bonustrack** [comment]
I dont see where you set an access token to the sdk

**Comment by rubenmr** [comment]
Sorry I'm stuck here. Where should I set an access token?

**Comment by bonustrack** [comment]
try `steem.setAccessToken(req.session.access_token)`

**Comment by rubenmr** [comment]
thanks sir, It runs fine!

i have a last question about posting
in this function:
steem.comment(
			'',
			primaryTag,
			author,
			permlink,
			title,
			body,
			json_metadata,
			(error, steemResponse)=>{

it also runs fine but i need to add beneficiaries 
for example:  beneficiaries=[{ account: 'abc', weight: 1000 }];

how can I do it? please, let me know.

**Comment by bgornicki** [comment]
The best way is to use `steem.broadcast` function with appropriate operations table. In your case, it should contain `comment` and `comment_options`. For example: 
```
const operations = [
    ['comment', {
        parent_author: parent_author,
        parent_permlink: parent_permlink,
        author: author,
        permlink: permlink,
        title: title,
        body: body,
        json_metadata: JSON.stringify({
            tags: [tag, second_tag],
            app: `engrave`
        })
    }],
    ['comment_options', {
        author: author,
        permlink: permlink,
        max_accepted_payout: '1000000.000 SBD',
        percent_steem_dollars: 10000,
        allow_votes: true,
        allow_curation_rewards: true,
        extensions: [
            [0, {
                beneficiaries: [{
                    account: 'abc', weight: 1000
                }]
            }]
        ]
    }]
];
```

Please note that if you want to post a top-level comment (an article), `parent_author` should be an empty string (`""`) and `parent_permlink` should be post's main tag.

**Comment by rubenmr** [comment]
thanks guys!!
