### ISSUE TITLE
login with posting key after initial authorization

### ISSUE THREAD

**Issue by economicstudio** [steemscript/steemconnect#365]
Hope there is some way for this: https://steemit.com/utopian-io/@blockchainstudio/security-misuse-of-steemconnect-login-shouldn-t-ask-active-key-for-every-login

In sum, even after the initial authorization of the posting right to an app, later login still requires active key, which I believe insecure. I know a workaround as I explained in the above post, but there should be an official way for users to login with posting key.

Thanks.

**Comment by economicstudio** [comment]
I heard that this feature will be available in SC3. When will it be available? Thanks!

**Comment by bonustrack** [comment]
It should be available this month @economicstudio, closing this issue it's duplicate of #259
