### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by ChilledMatter** [steemscript/steemconnect#367]
I'm experiencing a https://steemconnect.com/api/broadcast 401 error while trying to vote or comment. I've been looking for help in getting my app to work everywhere. It is built on React and is located here: https://github.com/ChilledMatter/AkibaSteem

I'd be grateful if anyone can have a look.

**Comment by jankulik** [comment]
I am facing the same problem in my application. Api.me request works properly, but when I am trying to upvote or comment I get a "Broadcaster account doesn't have permission to broadcast for <app name>" reply. And yes, I am logged with vote and comment permissions.

**Comment by bonustrack** [comment]
When did you created the app account? Does the app account authorize the account @steemconnect use his posting authorities? @ChilledMatter @jankulik

**Comment by ChilledMatter** [comment]
Well, I use my account with my app I created on steemconnect, so it should work.

**Comment by bonustrack** [comment]
Can you send me an access token along with the username of the app account on fabien@bonustrack.co? @ChilledMatter @jankulik

**Comment by ChilledMatter** [comment]
> Can you send me an access token along with the username of the app account on [fabien@bonustrack.co](mailto:fabien@bonustrack.co)? @ChilledMatter @jankulik

Sure. I just sent you from my email (odebla).

**Comment by bonustrack** [comment]
@ChilledMatter @jankulik thank you guys need to allow @steemconnect account for posting with the app account, here is a link to do that: https://app.steemconnect.com/authorize/@steemconnect Please let me know if it's not working after doing this operation.

**Comment by ChilledMatter** [comment]
Thanks a lot pal! It works! I think whoever's in charge of Steemconnect should make that link available in their documentation.

**Comment by jankulik** [comment]
It works for me too. Thank you!

**Comment by ChilledMatter** [comment]
Seems like we're done here. Closing the issue.
