### ISSUE TITLE
unauthorized_client error

### ISSUE THREAD

**Issue by rapunzelscodes** [steemscript/steemconnect#374]
### Steps to reproduce the behavior
I have login button 
its href  url has scope=vote,comment

when I click it,
SteemConnect popup opened.
I entered username and key

I returned my url (localhost:3000 / test.com )
and I have got token

--

I used api.me in NodeJS
and can get logged user's name and other things

api.me(function(err, res) {
loggeduser = res.user;
});

But can't work this:

parentPermlink="test";
author=loggeduser;
permlink="test";
title="test with sc";
body="steem connect test";
tagsMetadata='{tags:["test","test2"]}';
jsonMetadata=JSON.parse(tagsMetadata);
api.comment("", parentPermlink, author, permlink, title, body, jsonMetadata, function (err, res) {
console.log(err, res)
});

I get error:

[SDKError: sc2-sdk error]
name: 'SDKError',
error: 'unauthorized_client',
error_description:
"Broadcaster account doesn't have permission to broadcast

**Comment by rapunzelscodes** [comment]
I used this before api.comment:

```
api.setAccessToken(token,function (err, res) {
  console.log(err, res)
});
```


but get error again:

![permm](https://user-images.githubusercontent.com/49202793/55638041-37052e80-57be-11e9-8bad-f695d8f398fe.jpg)

**Comment by bonustrack** [comment]
What is the app account username @rapunzelscodes ?

**Comment by bonustrack** [comment]
The issue is most likely that the app account does not authorize "steemconnect" account to post on his behalf, to do so you need to sign this operation with your app account: https://app.steemconnect.com/authorize/@steemconnect

**Comment by rapunzelscodes** [comment]
I'm testing with @qbdp account. And I will create new real account.
I authorize to "steemconnect" right now. Thank you for interest.

**Comment by rapunzelscodes** [comment]
Yey!
After authorize to "steemconnect" https://app.steemconnect.com/authorize/@steemconnect
its working! Thank you so much!
